server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aichat?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      repositories:
        #forbid redis to scan repositories
        enabled: false
  redis:
    port: 6379
    host: localhost
    password: 123456
    database: 0
core:
  page-size:
    max: 1000
    default: 10
back:
  timeout: 3600